locallibrary/catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^all-borrowed/$', views.AllBorrowedBooksListView.as_view(), name='all-borrowed'),
    re_path(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    re_path(r'^author/create/$', views.AuthorCreate.as_view(), name='author-create'),
    re_path(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author-update'),
    re_path(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author-delete'),
    re_path(r'^book/create/$', views.BookCreate.as_view(), name='book-create'),
    re_path(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book-update'),
    re_path(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/locallibrary/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):

    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):

        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Book(models.Model):

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):

        return self.title


    def get_absolute_url(self):

        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

import uuid # Required for unique book instances


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)

    def get_status_display_with_color(self):
        status_dict = {
            'm': 'Maintenance',
            'o': 'On loan',
            'a': 'Available',
            'r': 'Reserved'
        }
        return status_dict.get(self.status, self.status)

    get_status_display_with_color.short_description = 'Status'
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):

        return '%s, %s' % (self.last_name, self.first_name)

    class Meta:
        ordering = ['last_name']

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime #for checking renewal date range.

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Проверка того, что дата не выходит за "нижнюю" границу (не в прошлом).
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Проверка того, то дата не выходит за "верхнюю" границу (+4 недели).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Помните, что всегда надо возвращать "очищенные" данные.
        return data

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db.models import Q  # Добавляем импорт Q
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Book, Author, BookInstance, Genre

def index(request):
    # Генерация "количеств" некоторых главных объектов
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()  # Добавляем количество жанров

    # Поиск книг по ключевым словам (ПЕРЕД return)
    search_words = ["война", "мир", "любовь", "death", "time", "science", "fantasy"]
    books_with_words = {}

    for word in search_words:
        count = Book.objects.filter(Q(title__icontains=word)).count()
        if count > 0:
            books_with_words[word] = count

    # Сортируем словарь по значениям (количеству книг) в убывающем порядке
    sorted_books_with_words = dict(sorted(
        books_with_words.items(),
        key=lambda item: item[1],
        reverse=True
    ))

    # Счетчик посещений
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'num_genres': num_genres,  # Добавляем количество жанров
            'num_visits': num_visits,
            'books_with_words': sorted_books_with_words,  # Добавляем отсортированный словарь
        },
    )

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book



class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 10


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


from django.contrib.auth.decorators import permission_required

from django.urls import reverse, reverse_lazy
import datetime

from .forms import RenewBookForm

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})


from django.contrib.auth.mixins import PermissionRequiredMixin


class AllBorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
    """
    Представление для отображения всех взятых книг, доступно только библиотекарям
    с разрешением can_mark_returned
    """
    model = BookInstance
    template_name = 'catalog/all_borrowed_books.html'
    context_object_name = 'borrowed_books'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        """Возвращаем только взятые книги (статус 'o' - on loan)"""
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial={'date_of_death':'12/10/2016',}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre']
    permission_required = 'catalog.add_book'

class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre']
    permission_required = 'catalog.change_book'

class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.delete_book'

locallibrary/catalog/templates/catalog/all_borrowed_books.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if borrowed_books %}
    <ul>
        {% for bookinst in borrowed_books %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> 
            - Due: {{ bookinst.due_back }}
            {% if bookinst.borrower %}
                - <strong>Borrower:</strong> {{ bookinst.borrower.get_username }}
            {% else %}
                - <strong>Borrower:</strong> Unknown
            {% endif %}
            {% if perms.catalog.can_mark_returned %}
                - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Author</h1>

  <p>Are you sure you want to delete the author: {{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{ author.last_name }}</h1>

  <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
  <p><strong>Date of death:</strong> {{ author.date_of_death }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <hr>
      <p><strong><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></strong></p>
      <p>{{ book.summary }}</p>
    {% endfor %}
  </div>

  {% if perms.catalog.change_author %}
      <a href="{% url 'author-update' author.pk %}">Edit</a>
  {% endif %}
  {% if perms.catalog.delete_author %}
      - <a href="{% url 'author-delete' author.pk %}">Delete</a>
  {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
        <p>({{author.date_of_birth}} -- {{author.date_of_death}})</p>
      </li>
      {% endfor %}

    </ul>
    {% else %}a
      <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Book</h1>

  <p>Are you sure you want to delete the book: <strong>{{ book }}</strong>?</p>
  
  {% if book.bookinstance_set.all %}
  <div class="alert alert-warning">
    <strong>Warning!</strong> This book has {{ book.bookinstance_set.count }} copy{{ book.bookinstance_set.count|pluralize }}. 
    Deleting this book will also delete all its copies.
  </div>
  <ul>
    {% for copy in book.bookinstance_set.all %}
      <li>{{ copy.imprint }} - {{ copy.get_status_display }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete">
    <a href="{{ book.get_absolute_url }}" >Cancel</a>
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong>
      {% if book.author %}
        <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a>
      {% else %}
        No author specified
      {% endif %}
    </p>

  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p>{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}

    {% if perms.catalog.change_book or perms.catalog.delete_book %}
        {% if perms.catalog.change_book %}
            <a href="{% url 'book-update' book.pk %}">Edit Book</a>
        {% endif %}
        {% if perms.catalog.delete_book %}
            <a href="{% url 'book-delete' book.pk %}">Delete Book</a>
        {% endif %}
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{% if object %}Edit Book{% else %}Create Book{% endif %}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <a href="{% if object %}{{ object.get_absolute_url }}{% else %}{% url 'books' %}{% endif %}">Cancel</a>
  </form>

{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if perms.catalog.add_book %}
        <a href="{% url 'book-create' %}">Add New Book</a>
    {% endif %}

    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
            {% if perms.catalog.change_book %}
                - <a href="{% url 'book-update' book.pk %}">Edit</a>
            {% endif %}
            {% if perms.catalog.delete_book %}
                - <a href="{% url 'book-delete' book.pk %}">Delete</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}